apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cluster.cnpg.yaml
  - backup.cnpg.yaml
  - objectstore.barman.yaml
  - secret-key.externalsecret.yaml
  - s3-credentials-pgauthentik-sync.yaml
  - email-credentials.externalsecret.yaml
  - httproute.yaml
  - tailscale-ingress.yaml
