apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cluster.cnpg.yaml
  - backup.cnpg.yaml
  - objectstore.barman.yaml
  - masterkey.externalsecret.yaml
  - s3-credentials-pgzitadel-sync.yaml
  - email-credentials.externalsecret.yaml
  - httproute.yaml
